[package]
edition = "2021"
name = "napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.5.0", default-features = false, features = ["napi4"] }
napi-derive = "2.5.0"

logic = { path = "../logic" }

[build-dependencies]
napi-build = "2.0.1"
